/** On-screen playbooks and engine explanations. Seeded product copy — not live ML. */

export type PlayStep = { en: string; th: string };

export type MenuPlaybook = {
  code: string;
  title: string;
  titleTh: string;
  why: string;
  whyTh: string;
  steps: PlayStep[];
  look: string;
  lookTh: string;
  seed: string;
  seedTh: string;
  engines?: string[];
};

export type EngineExplain = {
  id: string;
  n: string;
  en: string;
  th: string;
  href: string;
  phase: 1 | 2 | 3 | "signal";
  what: string;
  whatTh: string;
  why: string;
  whyTh: string;
  reads: string;
  readsTh: string;
  writes: string;
  writesTh: string;
  demo: string;
  demoTh: string;
  never: string;
  neverTh: string;
};

export const ENGINE_EXPLAIN: EngineExplain[] = [
  {
    id: "forecast", n: "01", phase: 1, href: "/rev-demand",
    en: "Demand Forecast Engine", th: "เครื่องพยากรณ์ดีมานด์",
    what: "Occupancy, room-nights, cancellations and demand by room type, segment and channel — for each arrival date.",
    whatTh: "เข้าพัก คืนห้อง ยกเลิก และดีมานด์ต่อประเภทห้อง เซ็กเมนต์ และช่องทาง — ต่อวันเข้า",
    why: "Pricing and inventory cannot guess. They need a number for “how many rooms will this date want?”",
    whyTh: "ราคาและห้องเดาไม่ได้ ต้องมีตัวเลขว่า “วันนี้จะมีคนอยากได้กี่ห้อง”",
    reads: "Pace, seasonality, events, competitor sold-out, pickup, remaining capacity.",
    readsTh: "จังหวะจอง ฤดูกาล อีเวนต์ คู่แข่งเต็ม ความเร็วจอง ห้องที่เหลือ",
    writes: "Nothing by itself. Feeds engines 05, 06, 10 and 12.",
    writesTh: "ไม่เขียนเอง ป้อนเครื่อง 05, 06, 10 และ 12",
    demo: "21 Aug · demand 44 RN · occ 94% · COMPRESSION · confidence High.",
    demoTh: "21 ส.ค. · ดีมานด์ 44 คืน · เข้าพัก 94% · ตลาดบีบ · ความมั่นใจสูง",
    never: "An LLM does not invent occupancy. This engine calculates; the Director only explains.",
    neverTh: "LLM ห้ามแต่งตัวเลขเข้าพัก เครื่องนี้คำนวณ ผู้อำนวยการอธิบายอย่างเดียว",
  },
  {
    id: "curve", n: "02", phase: 1, href: "/rev-demand",
    en: "Booking Curve + Pickup Engine", th: "เส้นโค้งจอง + ความเร็ว",
    what: "Where occupancy should sit at D-90…D-1 versus a normal year, plus bookings in the last 1h / 6h / 24h / 3d / 7d. Demand Acceleration Score 0–100.",
    whatTh: "เข้าพักควรอยู่ตรงไหนที่ D-90…D-1 เทียบปีปกติ และจองใน 1 ชม. / 6 ชม. / 24 ชม. / 3 วัน / 7 วัน คะแนนเร่งดีมานด์ 0–100",
    why: "A date that is 14 points ahead of the curve is already expensive. A date behind the curve is a mix or visibility problem — not always a discount.",
    whyTh: "วันที่นำเส้นโค้ง 14 จุดแพงอยู่แล้ว วันที่ตามหลังคือปัญหาส่วนผสมหรือการมองเห็น — ไม่ใช่ส่วนลดเสมอ",
    reads: "On-the-books occupancy by lead time, same-date last year, last 7 days of pickup.",
    readsTh: "เข้าพักตาม lead time ปีที่แล้ววันเดียวกัน ความเร็วจอง 7 วันล่าสุด",
    writes: "Nothing. Flags surge / stall for Pricing and Inventory.",
    writesTh: "ไม่เขียน ติดธงพุ่ง / ชะลอ ให้เครื่องราคาและห้อง",
    demo: "22 Aug at D-21 is 52% vs a normal 38%. Acceleration 81 — surge.",
    demoTh: "22 ส.ค. ที่ D-21 อยู่ 52% เทียบปกติ 38% คะแนนเร่ง 81 — พุ่ง",
    never: "Pickup is counted from the reservation store. The model does not “feel” busy.",
    neverTh: "ความเร็ว นับจากคลังการจอง โมเดลห้าม “รู้สึก” ว่ายุ่ง",
  },
  {
    id: "comp", n: "03", phase: 1, href: "/rev-demand",
    en: "Competitor Intelligence Engine", th: "ข่าวกรองคู่แข่ง",
    what: "Comp-set BAR, sold-out flags, length-of-stay rules and 12-hour price velocity. Signals — not a raw rate shop.",
    whatTh: "BAR คู่แข่ง ธงเต็ม กฎความยาวเข้าพัก และความเร็วราคา 12 ชม. เป็นสัญญาณ — ไม่ใช่แค่ตารางราคา",
    why: "Matching Ao Nang Cliff Beach +/− ฿100 is not a strategy. Four hotels lifting overnight is a compression signal for engine 05.",
    whyTh: "ตาม Ao Nang Cliff Beach +/− ฿100 ไม่ใช่กลยุทธ์ สี่โรงแรมขึ้นราคาข้ามคืนคือสัญญาณบีบให้เครื่อง 05",
    reads: "Public BAR of the six-hotel set, sold-out, LOS, timestamp of last change.",
    readsTh: "BAR สาธารณะของคู่แข่ง 6 แห่ง เต็ม LOS เวลาที่เปลี่ยนล่าสุด",
    writes: "Nothing. Feeds forecast and pricing.",
    writesTh: "ไม่เขียน ป้อนพยากรณ์และราคา",
    demo: "4 of 6 raised more than 12% in 12 hours. Two sold out overnight.",
    demoTh: "4 จาก 6 ขึ้นเกิน 12% ใน 12 ชม. สองแห่งเต็มข้ามคืน",
    never: "HOTEL24 never copies a competitor rate into ARI.",
    neverTh: "HOTEL24 ห้ามก็อปปี้ราคาคู่แข่งลง ARI",
  },
  {
    id: "event", n: "04", phase: 1, href: "/rev-demand",
    en: "Event Intelligence Engine", th: "ข่าวกรองอีเวนต์",
    what: "Concerts, races, holidays and food weeks near the hotel. Event Demand Impact Score for Pricing AI.",
    whatTh: "คอนเสิร์ต วิ่ง วันหยุด สัปดาห์อาหารใกล้โรงแรม คะแนนผลกระทบให้นักราคา AI",
    why: "Krabi Half Marathon 2.1 km away historically lifts demand ~19%. The hotel’s own impact is lower — 14% — because not every runner stays in Ao Nang.",
    whyTh: "คราบี้ฮาล์ฟมาราธอนห่าง 2.1 กม. เคยดึงดีมานด์ราว 19% ผลกระทบของโรงแรมนี้ต่ำกว่า — 14% — เพราะนักวิ่งไม่ได้อยู่กระบี่ทั้งหมด",
    reads: "Local calendar, distance, historical occupancy on the same event, remaining rooms.",
    readsTh: "ปฏิทินท้องถิ่น ระยะทาง เข้าพักย้อนหลังอีเวนต์เดียวกัน ห้องที่เหลือ",
    writes: "Nothing. Adjusts the forecast, then pricing.",
    writesTh: "ไม่เขียน ปรับพยากรณ์ แล้วค่อยราคา",
    demo: "Krabi Half Marathon · 2.1 km · historical +19% · hotel impact +14%.",
    demoTh: "คราบี้ฮาล์ฟ · 2.1 กม. · ประวัติ +19% · ผลกระทบโรงแรม +14%",
    never: "An event name in ChatGPT is not a rate. The score is numeric.",
    neverTh: "ชื่ออีเวนต์ใน ChatGPT ไม่ใช่ราคา คะแนนเป็นตัวเลข",
  },
  {
    id: "price", n: "05", phase: 1, href: "/rev-pricing",
    en: "Dynamic Pricing Engine", th: "เครื่องตั้งราคาไดนามิก",
    what: "Simulates a rate ladder and picks the price with the highest expected net — not competitor plus or minus ฿100.",
    whatTh: "จำลองบันไดราคา แล้วเลือกสุทธิคาดสูงสุด — ไม่ใช่คู่แข่งบวกหรือลบ ฿100",
    why: "฿2,550 looks “stronger” on Garden Monday and loses. ฿2,200 wins ฿41,800 expected net. That is the whole point.",
    whyTh: "฿2,550 ดูแรงกว่าบนสวนวันจันทร์แล้วแพ้ ฿2,200 ชนะสุทธิคาด ฿41,800 นั่นคือทั้งจุด",
    reads: "Forecast, curve, elasticity / WTP, competitor signals, floor rates, twin scenarios.",
    readsTh: "พยากรณ์ เส้นโค้ง ความยืดหยุ่น / WTP สัญญาณคู่แข่ง ราคาพื้น สถานการณ์ฝาแฝด",
    writes: "BAR on the ARI grid after Guardian. Demo: Garden 24–25 Aug ฿1,980 → ฿2,200.",
    writesTh: "BAR บนตาราง ARI หลัง Guardian เดโม: สวน 24–25 ส.ค. ฿1,980 → ฿2,200",
    demo: "Garden Monday ฿2,200 wins. Pool Friday ฿2,900 → ฿3,400 under compression.",
    demoTh: "สวนวันจันทร์ ฿2,200 ชนะ พูลวันศุกร์ ฿2,900 → ฿3,400 เมื่อตลาดบีบ",
    never: "The LLM never types ฿4,900. It may only explain why the engine picked a rung.",
    neverTh: "LLM ห้ามพิมพ์ ฿4,900 ได้อธิบายแค่ว่าทำไมเครื่องเลือกขั้นนั้น",
  },
  {
    id: "inv", n: "06", phase: 1, href: "/rev-inventory",
    en: "Inventory Optimization Engine", th: "เครื่องจัดสรรห้อง",
    what: "Open / close, MinLOS, protection, stop-sell and channel allotment. Sometimes this beats a price change.",
    whatTh: "เปิด / ปิด ขั้นต่ำ กันห้อง ปิดขาย และจัดสรรช่องทาง บางครั้งคุ้มกว่าการเปลี่ยนราคา",
    why: "One-night guests on a soft Monday steal the weekend length of stay the forecast already holds at a higher rate.",
    whyTh: "แขก 1 คืนวันจันทร์อ่อน ขโมยความยาวเข้าพักสุดสัปดาห์ที่พยากรณ์ไว้ที่ราคาสูงกว่า",
    reads: "ARI remaining, booking curve, group RFPs, channel Net ADR.",
    readsTh: "ARI ที่เหลือ เส้นโค้งจอง ใบขอกรุ๊ป Net ADR ต่อช่องทาง",
    writes: "Min-stay and allotment on the live store. Demo: Garden 24–25 Aug min-stay = 2.",
    writesTh: "ขั้นต่ำและจัดสรรบนคลังจริง เดโม: สวน 24–25 ส.ค. ขั้นต่ำ = 2",
    demo: "MinLOS 2 on Garden Mon–Tue protects weekend compression.",
    demoTh: "ขั้นต่ำ 2 คืนสวน จ–อ กันตลาดบีบสุดสัปดาห์",
    never: "Inventory AI does not dump rooms onto the cheapest OTA to “fill”.",
    neverTh: "ห้อง AI ห้ามเทห้องลง OTA ถูกสุดเพื่อ “เติมเต็ม”",
  },
  {
    id: "channel", n: "07", phase: 1, href: "/rev-distribution",
    en: "Channel Profitability Engine", th: "เครื่องกำไรต่อช่องทาง",
    what: "Net ADR after commission, promo, payment fees and ads. Direct and Agent Direct versus each OTA.",
    whatTh: "Net ADR หลังคอม โปร ค่าชำระ และโฆษณา จองตรงและ Agent Direct เทียบแต่ละ OTA",
    why: "Agoda can sell more and still leave ฿751 less profit per night. Gross ADR is a vanity number.",
    whyTh: "Agoda ขายมากกว่าแล้วยังเหลือกำไรต่ำกว่า ฿751 ต่อคืน ADR หน้าเว็บคือตัวเลขโอ้อวด",
    reads: "Channel mix, commission tables, promo cost, payment cost, remaining rooms.",
    readsTh: "ส่วนผสมช่องทาง ตารางคอม ต้นทุนโปร ต้นทุนชำระ ห้องที่เหลือ",
    writes: "Allotment moves after Guardian. Demo: Expedia’s 4 Garden rooms → Direct.",
    writesTh: "ย้ายจัดสรรหลัง Guardian เดโม: สวน 4 ห้องของ Expedia → จองตรง",
    demo: "Agent Direct net ฿2,576 · Agoda ฿1,493. Close Expedia first in compression.",
    demoTh: "Agent Direct สุทธิ ฿2,576 · Agoda ฿1,493 ปิด Expedia ก่อนเมื่อตลาดบีบ",
    never: "Never close every distribution channel at once. Guardian blocks that.",
    neverTh: "ห้ามปิดทุกช่องทางพร้อมกัน Guardian บล็อก",
  },
  {
    id: "guard", n: "08", phase: 1, href: "/rev-guardian",
    en: "Revenue Guardian Engine", th: "เครื่องรั้วรายได้",
    what: "A separate agent. Caps, floors, overbook limit, parity and anomaly. It never proposes a rate — it only stops one.",
    whatTh: "เอเจนต์แยก เพดาน พื้น ขีดขายเกิน พาร์ตี้ และความผิดปกติ ไม่เสนอราคา — ทำได้แค่หยุด",
    why: "If HOTEL24 writes ARI, something must refuse a ฿500 Suite and a sell limit of 52. That is this engine.",
    whyTh: "ถ้า HOTEL24 เขียน ARI ต้องมีอะไรปฏิเสธสวีท ฿500 และเพดานขาย 52 นี่คือเครื่องนี้",
    reads: "Owner floors, 30% single-change cap, +4 overbook cap, parity, date-span, the draft write.",
    readsTh: "ราคาพื้นของเจ้าของ เพดานขึ้น 30% ต่อครั้ง เพดานขายเกิน +4 พาร์ตี้ จำนวนวัน และร่างที่จะเขียน",
    writes: "Nothing to ARI. The ledger records BLOCKED.",
    writesTh: "ไม่เขียน ARI สมุดบันทึกว่าบล็อก",
    demo: "RD-839299 Suite ฿3,784 → ฿500 blocked (floor ฿3,200). Sell limit 52 blocked (cap +4).",
    demoTh: "RD-839299 สวีท ฿3,784 → ฿500 บล็อก (พื้น ฿3,200) เพดานขาย 52 บล็อก (เพดาน +4)",
    never: "There is no human override in this demo that types past the floor.",
    neverTh: "เดโมนี้ไม่มีปุ่มฝ่าฝืนที่พิมพ์ข้ามราคาพื้น",
  },
  {
    id: "cancel", n: "09", phase: 2, href: "/rev-cancel",
    en: "Cancellation Prediction Engine", th: "เครื่องทำนายยกเลิก",
    what: "A cancel probability on every reservation: channel, lead time, refundable flag, price versus the guest’s last stays, house history.",
    whatTh: "โอกาสยกเลิกต่อการจอง: ช่องทาง lead time คืนเงินได้ ราคาเทียบสามครั้งก่อน ประวัติบ้าน",
    why: "A 67% Agoda refundable is soft inventory for overbooking — not a room you re-list at BAR.",
    whyTh: "Agoda คืนเงินได้ 67% คือห้องนิ่มสำหรับขายเกิน — ไม่ใช่ห้องที่ปล่อย BAR ซ้ำ",
    reads: "Folio channel, lead days, refundable, rate vs guest history, cancel history.",
    readsTh: "ช่องทางโฟลิโอ จำนวนวันล่วงหน้า คืนเงินได้ ราคาเทียบประวัติแขก ประวัติยกเลิก",
    writes: "A flag / note. Overbooking may count 0.67 of that room as wash.",
    writesTh: "ธง / บันทึก เครื่องขายเกินนับ 0.67 ของห้องนั้นเป็นที่อาจว่าง",
    demo: "H24-8860 Lim Wei Jie · Agoda · refundable · 21-day lead · 67%.",
    demoTh: "H24-8860 Lim Wei Jie · Agoda · คืนเงินได้ · lead 21 วัน · 67%",
    never: "Scores are seeded — not a live LightGBM. Do not treat 67% as a live model.",
    neverTh: "คะแนนจำลอง — ไม่ใช่ LightGBM จริง อย่าถือ 67% เป็นโมเดลสด",
  },
  {
    id: "overbook", n: "10", phase: 2, href: "/rev-overbook",
    en: "Overbooking Engine", th: "เครื่องขายเกินคำนวณ",
    what: "Expected cancel + no-show versus walk-cost. Optimal sell limit on a 42-room house. Guardian caps rooms above physical.",
    whatTh: "ยกเลิก + no-show ที่คาด เทียบต้นทุนวอล์ก เพดานขายที่เหมาะบนบ้าน 42 ห้อง Guardian จำกัดห้องเกินของจริง",
    why: "44 already on the books for Friday. Expected wash 3.2. Sitting at 42 leaves money on the table. Sitting at 52 walks the house.",
    whyTh: "วันศุกร์จองแล้ว 44 คาดว่าง 3.2 อยู่ที่ 42 คือทิ้งเงิน อยู่ที่ 52 คือวอล์กทั้งบ้าน",
    reads: "Cancel scores, no-show rate, empty-room cost, walk-cost, physical rooms, owner cap +4.",
    readsTh: "คะแนนยกเลิก อัตรา no-show ต้นทุนห้องว่าง ต้นทุนวอล์ก ห้องจริง เพดานเจ้าของ +4",
    writes: "Sell limit on that date. Demo: 21 Aug → 45. Sell 52 is blocked.",
    writesTh: "เพดานขายของวันนั้น เดโม: 21 ส.ค. → 45 เพดาน 52 ถูกบล็อก",
    demo: "21 Aug · 44 on books · wash 3.2 · empty ฿2,200 · walk ฿6,800 · sell 45.",
    demoTh: "21 ส.ค. · จอง 44 · คาดว่าง 3.2 · ห้องว่าง ฿2,200 · วอล์ก ฿6,800 · เพดาน 45",
    never: "The LLM does not pick “sell 45”. The engine does. Guardian refuses +10.",
    neverTh: "LLM ห้ามเลือก “ขาย 45” เครื่องเลือก Guardian ปฏิเสธ +10",
  },
  {
    id: "elastic", n: "11", phase: 2, href: "/rev-elasticity",
    en: "Price Elasticity / WTP Engine", th: "ความยืดหยุ่นราคา / WTP",
    what: "Learned conversion drop per price step, by segment, nationality, channel and lead time.",
    whatTh: "คอนเวอร์ชันที่ตกต่อขั้นราคา ตามเซ็กเมนต์ สัญชาติ ช่องทาง และ lead time",
    why: "Leisure / mobile / Agoda at D-7 dies at ฿2,550 on a soft weekday. The +11% step to ฿2,200 is the learned safe move.",
    whyTh: "เที่ยว / มือถือ / Agoda ที่ D-7 ตายที่ ฿2,550 ในวันธรรมดาอ่อน ขั้น +11% ไป ฿2,200 คือขั้นที่ปลอดภัย",
    reads: "Historical conversion by price rung, segment, channel, lead time.",
    readsTh: "คอนเวอร์ชันย้อนหลังต่อขั้นราคา เซ็กเมนต์ ช่องทาง lead time",
    writes: "A breakpoint log — not a new BAR. Keeps the Phase 1 ฿2,200 write.",
    writesTh: "บันทึกจุดหัก — ไม่ใช่ BAR ใหม่ คงการเขียนเฟส 1 ที่ ฿2,200",
    demo: "฿1,980→฿2,200 = −3% (safe). ฿2,550→฿2,900 = −19% (breakpoint).",
    demoTh: "฿1,980→฿2,200 = −3% (ปลอดภัย) ฿2,550→฿2,900 = −19% (จุดหัก)",
    never: "Pricing AI may not jump a breakpoint because a competitor moved.",
    neverTh: "เอเจนต์ราคาห้ามกระโดดจุดหักเพราะคู่แข่งขยับ",
  },
  {
    id: "group", n: "12", phase: 2, href: "/rev-group",
    en: "Group Displacement Engine", th: "เครื่องวัดการเบียดแขกเดิน",
    what: "Group room revenue + F&B − displaced transient − cost. Verdict: reject / accept-above / counter.",
    whatTh: "รายได้ห้องกรุ๊ป + อาหาร − แขกเดินที่เบียด − ต้นทุน คำตัดสิน: ปฏิเสธ / รับเมื่อเกิน / เสนอราคา",
    why: "12 rooms × 2 nights at ฿2,700 looks like occupancy. It displaces walk-in demand already forecast at ฿2,200–฿3,400.",
    whyTh: "12 ห้อง × 2 คืนที่ ฿2,700 ดูเหมือนเข้าพัก แต่เบียดดีมานด์เดินที่พยากรณ์ไว้ ฿2,200–฿3,400",
    reads: "RFP rooms, nights, offered rate, F&B, forecast transient value, cost.",
    readsTh: "ห้องในใบขอ จำนวนคืน ราคาที่เสนอ อาหาร มูลค่าแขกเดินในพยากรณ์ ต้นทุน",
    writes: "A reject + counter note. No inventory until sales accepts.",
    writesTh: "บันทึกปฏิเสธ + ราคาเสนอ ยังไม่เขียนห้องจนกว่าฝ่ายขายรับ",
    demo: "ABC Incentive · reject ฿2,700 · accept above ฿3,550 · net if taken −฿8,600.",
    demoTh: "ABC Incentive · ปฏิเสธ ฿2,700 · รับเมื่อเกิน ฿3,550 · สุทธิถ้ารับ −฿8,600",
    never: "“Take the group, we need the occupancy” is not a number. This engine is.",
    neverTh: "“รับกรุ๊ปเถอะ เราต้องการเข้าพัก” ไม่ใช่ตัวเลข เครื่องนี้คือตัวเลข",
  },
  {
    id: "alloc", n: "13", phase: 2, href: "/rev-alloc",
    en: "Channel Allocation Engine", th: "เครื่องจัดสรรช่องทาง",
    what: "How many rooms Booking / Agoda / Expedia / Direct may hold as the market moves from weak → normal → compression → surge.",
    whatTh: "Booking / Agoda / Expedia / จองตรง กันห้องได้กี่ห้องเมื่อตลาดเดินจากอ่อน → ปกติ → บีบ → พุ่ง",
    why: "Last rooms go to the highest Net ADR. Booking stays open — Guardian never lets you close every OTA.",
    whyTh: "ห้องท้ายไปช่อง Net ADR สูงสุด Booking ยังเปิด — Guardian ไม่ให้ปิดทุก OTA",
    reads: "Compression state, Net ADR by channel, current allotment, remaining Garden rooms.",
    readsTh: "สภาวะบีบตลาด Net ADR ต่อช่อง จัดสรรปัจจุบัน ห้องสวนที่เหลือ",
    writes: "Allotment on the live store. Demo: Booking 12 → 8, Direct 14 → 18.",
    writesTh: "จัดสรรบนคลังจริง เดโม: Booking 12 → 8 จองตรง 14 → 18",
    demo: "Compression pick: Booking 8 · Agoda 8 · Expedia 0 · Direct 18.",
    demoTh: "เลือกตอนตลาดบีบ: Booking 8 · Agoda 8 · Expedia 0 · จองตรง 18",
    never: "Do not close Booking entirely to “protect Direct”. That trips the Guardian close-all rule.",
    neverTh: "ห้ามปิด Booking ทั้งก้อนเพื่อ “กันจองตรง” นั้นชนกฎห้ามปิดทุกช่องของ Guardian",
  },
  {
    id: "promo", n: "14", phase: 2, href: "/rev-promo",
    en: "Promotion Optimization Engine", th: "เครื่องโปรโมชัน",
    what: "Diagnoses PRICE versus DEMAND. Simulates 20% off, 10% off, ads, Stay 3 Pay 2, and breakfast with no cut.",
    whatTh: "วินิจฉัยว่าราคาหรือดีมานด์ จำลองลด 20% ลด 10% โฆษณา พัก 3 จ่าย 2 และอาหารเช้าโดยไม่ตัดราคา",
    why: "Monday occupancy is a mix / visibility problem. 20% off buys +4pp occupancy and loses ฿18,200 net.",
    whyTh: "เข้าพักวันจันทร์คือปัญหาส่วนผสม / การมองเห็น ลด 20% ซื้อเข้าพัก +4 จุด แล้วเสียสุทธิ ฿18,200",
    reads: "Weekday curve, twin, channel mix, breakfast cost, parity with Agoda.",
    readsTh: "เส้นโค้งวันธรรมดา ฝาแฝด ส่วนผสมช่องทาง ต้นทุนอาหารเช้า พาร์ตี้กับ Agoda",
    writes: "A Direct inclusion (breakfast). No BAR cut. Demo: Option C.",
    writesTh: "สิทธิ์บนจองตรง (อาหารเช้า) ไม่ตัด BAR เดโม: ตัวเลือก C",
    demo: "Option C breakfast, no discount: +฿6,400. Option A 20% off: −฿18,200.",
    demoTh: "ตัวเลือก C อาหารเช้า ไม่ลด: +฿6,400 ตัวเลือก A ลด 20%: −฿18,200",
    never: "A discount is not the default answer to a soft date.",
    neverTh: "ส่วนลดไม่ใช่คำตอบตั้งต้นของวันที่อ่อน",
  },
  {
    id: "direct", n: "15", phase: 2, href: "/rev-convert",
    en: "Direct Conversion Engine", th: "เครื่องแปลงจองตรง",
    what: "Abandoned searches and price-sensitive sessions get an inclusion — not a cheaper public BAR. Feeds Agent Direct.",
    whatTh: "เซสชันที่ทิ้งตะกร้าและอ่อนไหวราคาได้สิทธิ์ — ไม่ตัด BAR หน้าเว็บ ต่อเข้า Agent Direct",
    why: "A ฿200 public cut matches Agoda and breaks parity. Free-cancel on one session recovers the guest and keeps the rate.",
    whyTh: "ตัด ฿200 หน้าเว็บไปเท่า Agoda แล้วพาร์ตี้พัง ยกเลิกฟรีบนเซสชันเดียวดึงแขกกลับและรักษาเรท",
    reads: "Session source, device, lead time, drop point, room, conversion model.",
    readsTh: "แหล่งเซสชัน อุปกรณ์ lead time จุดทิ้ง ห้อง โมเดลแปลง",
    writes: "A Direct / Agent Direct offer on that session id. Demo: S-4419 free-cancel 24h.",
    writesTh: "ข้อเสนอจองตรง / Agent Direct บนไอดีเซสชันนั้น เดโม: S-4419 ยกเลิกฟรี 24 ชม.",
    demo: "Sydney mobile · D-18 · Garden 24 Aug · dropped on payment · 71% if flexible cancel.",
    demoTh: "มือถือซิดนีย์ · D-18 · สวน 24 ส.ค. · ทิ้งตอนจ่าย · 71% ถ้ายกเลิกยืดหยุ่น",
    never: "Guardian blocks a public undercut of the OTA rate.",
    neverTh: "Guardian บล็อกการตัดราคา OTA บนหน้าเว็บ",
  },
  {
    id: "attr", n: "16", phase: 2, href: "/rev-attribution",
    en: "Revenue Attribution Engine", th: "เครื่องอธิบายรายได้",
    what: "Splits a revenue miss or beat into market, price, mix, channel, promo, cancel, group, Direct and upsell.",
    whatTh: "แยกส่วนต่างรายได้เป็นตลาด ราคา ส่วนผสม ช่องทาง โปร ยกเลิก กรุ๊ป จองตรง และอัปเซล",
    why: "The Director cannot learn if every miss is “the market”. Attribution is how the loop closes.",
    whyTh: "ผู้อำนวยการเรียนรู้ไม่ได้ถ้าทุกส่วนต่างคือ “ตลาด” เครื่องนี้ปิดวงจร",
    reads: "Budget, actual, pickup, channel mix, cancel wash, group take-up, Direct share.",
    readsTh: "งบ จริง ความเร็วจอง ส่วนผสมช่องทาง ห้องที่ว่างจากยกเลิก กรุ๊ปที่รับ ส่วนจองตรง",
    writes: "Nothing to ARI. Explanation only.",
    writesTh: "ไม่เขียน ARI อธิบายอย่างเดียว",
    demo: "Next month −8.7% vs budget: SG demand −4.1 · OTA visibility −2.3 · corporate −1.5 · other −0.8.",
    demoTh: "เดือนหน้าต่ำกว่างบ 8.7%: ดีมานด์สิงคโปร์ −4.1 · การมองเห็น OTA −2.3 · คอร์ปอเรต −1.5 · อื่น −0.8",
    never: "This is seeded variance — not a live econometric model.",
    neverTh: "ส่วนต่างจำลอง — ไม่ใช่โมเดลเศรษฐมิติจริง",
  },
  {
    id: "compress", n: "—", phase: "signal", href: "/rev-demand",
    en: "Market Compression Engine", th: "เครื่องวัดการบีบตลาด",
    what: "A supporting 0–100 score on how tight Ao Nang is that night. Not one of the official sixteen.",
    whatTh: "คะแนนเสริม 0–100 ว่าคืนนั้นกระบี่แน่นแค่ไหน ไม่ใช่หนึ่งในสิบหกทางการ",
    why: "Pricing and overbooking need a market-tightness number besides the hotel’s own occupancy.",
    whyTh: "ราคาและขายเกินต้องมีตัวเลขความแน่นของตลาด นอกจากเข้าพักของบ้านเอง",
    reads: "Comp-set occupancy / sold-out, event score, pickup across the set.",
    readsTh: "เข้าพัก / เต็มของคู่แข่ง คะแนนอีเวนต์ ความเร็วจองทั้งชุด",
    writes: "Nothing. Lives on Demand Brain.",
    writesTh: "ไม่เขียน อยู่บนสมองดีมานด์",
    demo: "Ao Nang 21 Aug = 78 / 100.",
    demoTh: "อ่าวนาง 21 ส.ค. = 78 / 100",
    never: "Do not treat compression as a live market feed. It is seeded.",
    neverTh: "อย่าถือดัชนีบีบเป็นฟีดตลาดสด เป็นข้อมูลจำลอง",
  },
  {
    id: "twin", n: "—", phase: 3, href: "/rev-twin",
    en: "Hotel Digital Twin Engine", th: "ฝาแฝดดิจิทัลโรงแรม",
    what: "Before the Director writes, simulate hold / +11% / +29% (or any ladder) on expected occ, RevPAR and net.",
    whatTh: "ก่อนผู้อำนวยการเขียน จำลองคงราคา / +11% / +29% (หรือบันไดใดก็ได้) บนเข้าพักคาด RevPAR และสุทธิ",
    why: "Scenario C looks aggressive and loses. The twin is why ฿2,200 ships and ฿2,550 does not.",
    whyTh: "สถานการณ์ C ดูแรงแล้วแพ้ ฝาแฝดคือเหตุผลที่ ฿2,200 ถูกเขียน และ ฿2,550 ไม่ถูก",
    reads: "Price ladder, elasticity, forecast rooms, cost.",
    readsTh: "บันไดราคา ความยืดหยุ่น ห้องในพยากรณ์ ต้นทุน",
    writes: "Nothing. The Director writes the winning scenario after Guardian.",
    writesTh: "ไม่เขียน ผู้อำนวยการเขียนสถานการณ์ที่ชนะหลัง Guardian",
    demo: "Garden Monday: hold RevPAR ฿1,465 · B +11% ฿1,496 wins · C +29% loses.",
    demoTh: "สวนวันจันทร์: คงราคา RevPAR ฿1,465 · B +11% ฿1,496 ชนะ · C +29% แพ้",
    never: "Phase 3 label: this is a seeded weekday Garden curve, not a live Monte Carlo.",
    neverTh: "ป้ายเฟส 3: เส้นโค้งสวนวันธรรมดาจำลอง ไม่ใช่ Monte Carlo สด",
  },
];

export function explainEngine(id: string) {
  return ENGINE_EXPLAIN.find((e) => e.id === id);
}

export function explainEngines(ids: string[]) {
  return ids.map(explainEngine).filter((e): e is EngineExplain => !!e);
}

export const MENU_PLAYBOOKS: Record<string, MenuPlaybook> = {
  "/agent-direct": {
    code: "PB-AD",
    title: "Agent Direct",
    titleTh: "Agent Direct",
    why: "This is how a hotel becomes bookable by ChatGPT, Gemini and any MCP agent — without giving the guest to an OTA.",
    whyTh: "หน้านี้ทำให้โรงแรมจองผ่าน ChatGPT, Gemini และเอเจนต์ MCP ได้ โดยไม่ยกแขกให้ OTA",
    steps: [
      { en: "Confirm the hotel is AI Agent Ready (toggle on this page).", th: "ยืนยันว่าโรงแรมพร้อมให้เอเจนต์จอง (สวิตช์ในหน้านี้)" },
      { en: "Open hotel24.json — that is the identity agents fetch.", th: "เปิด hotel24.json — คือตัวตนที่เอเจนต์ดึง" },
      { en: "Walk Gateway → Registry → Offers → AEO → HAP if you are showing a partner.", th: "เดินเกตเวย์ → ทะเบียน → ข้อเสนอ → AEO → HAP ถ้าโชว์พาร์ทเนอร์" },
    ],
    look: "Baan Talay publishes identity, live rooms, rates, cancel policy and a booking API. Booking.com is not required.",
    lookTh: "บ้านทะเลปล่อยตัวตน ห้องสด ราคา นโยบายยกเลิก และ API จอง ไม่ต้องมี Booking.com",
    seed: "HAP 0.1.0 on this demo. Not a certified OpenAI / Google listing.",
    seedTh: "HAP 0.1.0 บนเดโมนี้ ยังไม่ใช่ลิสต์รับรองของ OpenAI / Google",
  },
  "/gateway": {
    code: "PB-GW",
    title: "Agent Gateway",
    titleTh: "เกตเวย์เอเจนต์",
    why: "The door agents knock on. Tools in, hold and booking out, into this PMS as Direct.",
    whyTh: "ประตูที่เอเจนต์เคาะ เครื่องมือเข้า กันห้องและจองออก เข้า PMS นี้เป็นการจองตรง",
    steps: [
      { en: "Read the tool list — search, quote, hold, book, cancel.", th: "อ่านรายการเครื่องมือ — ค้นหา ใบราคา กันห้อง จอง ยกเลิก" },
      { en: "Use the public playground at /agents to book Chiang Mai as an agent.", th: "ใช้สนามเล่นสาธารณะ /agents จองเชียงใหม่แบบเอเจนต์" },
      { en: "A successful book lands on Reservations as Agent Direct · commission ฿0.", th: "จองสำเร็จไปอยู่ปฏิทินเป็นการจอง Agent Direct · คอม ฿0" },
    ],
    look: "Traveler → agent → Gateway → PMS → Direct. You own the guest.",
    lookTh: "ผู้เดินทาง → เอเจนต์ → เกตเวย์ → PMS → จองตรง คุณเป็นเจ้าของแขก",
    seed: "Invoke is mapped, not a live ChatGPT plugin review.",
    seedTh: "การเรียกถูกแมปไว้ ยังไม่ใช่ปลั๊กอิน ChatGPT ที่ผ่านรีวิว",
  },
  "/registry": {
    code: "PB-REG",
    title: "AI Registry",
    titleTh: "ทะเบียน AI",
    why: "Verified hotels an agent is allowed to ask. Unverified properties do not appear.",
    whyTh: "โรงแรมที่ยืนยันแล้ว เอเจนต์ถามได้ โรงแรมที่ไม่ยืนยันจะไม่โผล่",
    steps: [
      { en: "Confirm Baan Talay is listed and verified.", th: "ตรวจว่าบ้านทะเลอยู่ในรายการและยืนยันแล้ว" },
      { en: "GET /api/hap/registry is the machine copy of this page.", th: "GET /api/hap/registry คือสำเนาเครื่องของหน้านี้" },
    ],
    look: "Ao Nang plus Chiang Mai boutiques, a hostel and villas — the seeded graph.",
    lookTh: "อ่าวนางบวกบูทีคเชียงใหม่ โฮสเทล และวิลล่า — กราฟจำลอง",
    seed: "Registry is HOTEL24’s own list, not Google Hotel Ads.",
    seedTh: "ทะเบียนเป็นของ HOTEL24 เอง ไม่ใช่ Google Hotel Ads",
  },
  "/agent-offers": {
    code: "PB-OFF",
    title: "Direct Offers",
    titleTh: "ข้อเสนอตรง",
    why: "Same public rate as the OTA, a better inclusion. Agents can read it. You do not undercut BAR.",
    whyTh: "ราคาหน้าเว็บเท่า OTA สิทธิ์ดีกว่า เอเจนต์อ่านได้ คุณไม่ตัด BAR",
    steps: [
      { en: "Read the breakfast / late-checkout inclusions.", th: "อ่านสิทธิ์อาหารเช้า / เช็คเอาท์ช้า" },
      { en: "Approve the RevenueOS breakfast write from the Director if it is still pending.", th: "อนุมัติการเขียนอาหารเช้าจากผู้อำนวยการถ้ายังค้าง" },
    ],
    look: "Parity stays. Conversion happens on the inclusion — engine 15 uses the same idea.",
    lookTh: "พาร์ตี้คงอยู่ การแปลงเกิดที่สิทธิ์ — เครื่อง 15 ใช้แนวเดียวกัน",
    seed: "Offers are seeded on Baan Talay, not a live offer engine.",
    seedTh: "ข้อเสนอจำลองบนบ้านทะเล ไม่ใช่เครื่องข้อเสนอสด",
  },
  "/aeo": {
    code: "PB-AEO",
    title: "AEO",
    titleTh: "AEO",
    why: "Agent Engine Optimization sits beside SEO. Robots and files that tell an AI how to find and book you.",
    whyTh: "AEO อยู่ข้าง SEO ไฟล์และหุ่นยนต์ที่บอก AI ว่าจะหาและจองคุณอย่างไร",
    steps: [
      { en: "Open /.well-known/hotel24.json, llms.txt, sitemap.", th: "เปิด /.well-known/hotel24.json, llms.txt, sitemap" },
      { en: "Check OAI-SearchBot and MCP discovery rewrites.", th: "ตรวจ OAI-SearchBot และการค้นพบ MCP" },
    ],
    look: "The owner never has to learn these names. Connecting HOTEL24 publishes them.",
    lookTh: "เจ้าของไม่ต้องไปเรียนชื่อพวกนี้ เชื่อม HOTEL24 แล้วระบบปล่อยให้",
    seed: "Files are real on this deploy. They are not a ranking guarantee.",
    seedTh: "ไฟล์มีจริงบนดีพลอยนี้ ไม่ได้รับประกันอันดับ",
  },
  "/hap": {
    code: "PB-HAP",
    title: "HAP spec",
    titleTh: "สเปก HAP",
    why: "Hotel Agent Protocol — open spec on Schema.org, MCP, ACP and UCP. HOTEL24’s contract with agents.",
    whyTh: "Hotel Agent Protocol — สเปกเปิดบน Schema.org, MCP, ACP และ UCP สัญญาของ HOTEL24 กับเอเจนต์",
    steps: [
      { en: "Skim tools: search_hotels → create_room_hold → create_booking.", th: "กวาดตาเครื่องมือ: search_hotels → create_room_hold → create_booking" },
      { en: "Aliases create_quote / hold_room / book_room exist for sloppy agents.", th: "มีชื่อสำรอง create_quote / hold_room / book_room สำหรับเอเจนต์ที่เรียกไม่ตรง" },
    ],
    look: "This is a spec page, not a dashboard. Gateway is where it runs.",
    lookTh: "นี่คือหน้าสเปก ไม่ใช่แดชบอร์ด เกตเวย์คือที่ที่มันวิ่ง",
    seed: "HAP 0.1.0. Mapped, not certified.",
    seedTh: "HAP 0.1.0 แมปแล้ว ยังไม่รับรอง",
  },
  "/rev-engines": {
    code: "PB-R1",
    title: "Phase 1 engines",
    titleTh: "เครื่องยนต์เฟส 1",
    why: "Eight calculators plus a Director. Open each row. The LLM does not set the rate.",
    whyTh: "แปดเครื่องคิดบวกผู้อำนวยการ เปิดแต่ละแถว LLM ห้ามตั้งราคา",
    steps: [
      { en: "Read 01–08 below — what each calculates, writes, and refuses.", th: "อ่าน 01–08 ด้านล่าง — แต่ละตัวคำนวณอะไร เขียนอะไร และปฏิเสธอะไร" },
      { en: "Open an engine page, then approve the write on the Director.", th: "เปิดหน้าเครื่องยนต์ แล้วไปอนุมัติงานเขียนที่ผู้อำนวยการ" },
      { en: "Phase 2 (09–16) is a separate catalog.", th: "เฟส 2 (09–16) อยู่รายการแยก" },
    ],
    look: "Guardian (08) is mandatory if anything writes ARI.",
    lookTh: "Guardian (08) บังคับถ้ามีการเขียน ARI",
    seed: "Seeded department on Baan Talay. Not live LightGBM.",
    seedTh: "ฝ่ายจำลองบนบ้านทะเล ไม่ใช่ LightGBM สด",
    engines: ["forecast", "curve", "comp", "event", "price", "inv", "channel", "guard"],
  },
  "/rev-phase2": {
    code: "PB-R2",
    title: "Phase 2 engines",
    titleTh: "เครื่องยนต์เฟส 2",
    why: "Eight more so the hotel can score cancels, overbook, judge groups, allocate, promo, convert Direct and explain the miss.",
    whyTh: "อีกแปดตัวให้โรงแรมให้คะแนนยกเลิก ขายเกิน ตัดสินกรุ๊ป จัดสรร โปร แปลงจองตรง และอธิบายส่วนต่าง",
    steps: [
      { en: "Read 09–16 below. Approve writes on this page or on the Director.", th: "อ่าน 09–16 ด้านล่าง อนุมัติงานเขียนในหน้านี้หรือที่ผู้อำนวยการ" },
      { en: "Try sell limit 45 (allowed) versus 52 (blocked).", th: "ลองเพดานขาย 45 (ได้) เทียบ 52 (บล็อก)" },
    ],
    look: "Guardian still refuses Suite ฿500 and sell 52.",
    lookTh: "Guardian ยังปฏิเสธสวีท ฿500 และเพดาน 52",
    seed: "Seeded — not live cancel ML or a live overbook optimiser.",
    seedTh: "จำลอง — ไม่ใช่ ML ยกเลิกสด หรือตัวขายเกินสด",
    engines: ["cancel", "overbook", "elastic", "group", "alloc", "promo", "direct", "attr"],
  },
  "/revenue-os": {
    code: "PB-DIR",
    title: "Revenue Director",
    titleTh: "ผู้อำนวยการรายได้",
    why: "The commercial department. Agents explain. Engines calculate. Guardian blocks. Execution writes. Default is Level 2.",
    whyTh: "ฝ่ายพาณิชย์ เอเจนต์อธิบาย เครื่องยนต์คำนวณ Guardian บล็อก การลงมือเขียน ค่าเริ่มต้นคือระดับ 2",
    steps: [
      { en: "Leave autonomy on L2 unless you want to approve each write (L1) or only watch (L0).", th: "ปล่อยอัตโนมัติที่ L2 เว้นแต่จะอนุมัติทีละรายการ (L1) หรือดูอย่างเดียว (L0)" },
      { en: "Run the morning meeting — at L2 it applies pending writes that pass Guardian.", th: "เปิดประชุมเช้า — ที่ L2 มันเขียนรายการค้างที่ผ่าน Guardian" },
      { en: "Or approve one card. Blocked cards never get a button.", th: "หรืออนุมัติทีละการ์ด การ์ดที่บล็อกไม่มีปุ่ม" },
    ],
    look: "Suite ฿500 and sell 52 stay on the ledger as blocked. Expected profit is incremental, not total revenue.",
    lookTh: "สวีท ฿500 และเพดาน 52 อยู่ในสมุดว่าบล็อก กำไรที่คาดคือส่วนเพิ่ม ไม่ใช่รายได้ทั้งก้อน",
    seed: "Meeting copy and numbers are seeded. Classic /autopilot is the older single queue.",
    seedTh: "ข้อความประชุมและตัวเลขจำลอง /autopilot เดิมคือคิวเดียวแบบเก่า",
  },
  "/rev-demand": {
    code: "PB-01",
    title: "Demand Brain",
    titleTh: "สมองดีมานด์",
    why: "Who will book, when, and how much. Engines 01–04 live here. Compression is a supporting signal.",
    whyTh: "ใครจะจอง เมื่อไหร่ เท่าไหร่ เครื่อง 01–04 อยู่ที่นี่ การบีบตลาดเป็นสัญญาณเสริม",
    steps: [
      { en: "Read Friday 21 Aug — 94% and COMPRESSION.", th: "อ่านวันศุกร์ 21 ส.ค. — 94% และตลาดบีบ" },
      { en: "Compare the 22 Aug curve (52% vs 38%) and the pickup windows.", th: "เทียบเส้นโค้ง 22 ส.ค. (52% ต่อ 38%) และหน้าต่างความเร็ว" },
      { en: "Comp-set and the Half Marathon are inputs to price — not rates themselves.", th: "คู่แข่งและฮาล์ฟมาราธอนเป็นอินพุตราคา — ไม่ใช่ราคาเอง" },
    ],
    look: "Acceleration 81 · compression 78. Soft Monday is later — that is a promo / mix problem.",
    lookTh: "ความเร่ง 81 · ดัชนีบีบ 78 วันจันทร์อ่อนอยู่ข้างหน้า — นั่นคือโปร / ส่วนผสม",
    seed: "Ensemble of pace + event + competitor + seasonal baseline. Not live LightGBM.",
    seedTh: "ชุดรวมจังหวะ + อีเวนต์ + คู่แข่ง + ฤดูกาล ไม่ใช่ LightGBM สด",
    engines: ["forecast", "curve", "comp", "event", "compress"],
  },
  "/rev-pricing": {
    code: "PB-05",
    title: "Price Brain",
    titleTh: "สมองราคา",
    why: "Engine 05 picks the ladder rung with the highest expected net. The twin is why ฿2,200 beats ฿2,550.",
    whyTh: "เครื่อง 05 เลือกขั้นบันไดที่สุทธิคาดสูงสุด ฝาแฝดคือเหตุผลที่ ฿2,200 ชนะ ฿2,550",
    steps: [
      { en: "Read the Garden Monday ladder. The highlighted row is the pick.", th: "อ่านบันไดสวนวันจันทร์ แถวที่ไฮไลต์คือตัวเลือก" },
      { en: "Approve the write on the card — it lands on the ARI grid.", th: "อนุมัติงานเขียนบนการ์ด — ไปลงตาราง ARI" },
      { en: "Open engine 11 if you want the breakpoint that forbids ฿2,550.", th: "เปิดเครื่อง 11 ถ้าต้องการจุดหักที่ห้าม ฿2,550" },
    ],
    look: "Floor rates live on Guardian. +11% is under the 30% single-change cap.",
    lookTh: "ราคาพื้นอยู่ที่ Guardian +11% ต่ำกว่าเพดานขึ้น 30% ต่อครั้ง",
    seed: "Ladder is seeded for Garden 24 Aug.",
    seedTh: "บันไดจำลองสำหรับสวน 24 ส.ค.",
    engines: ["price"],
  },
  "/rev-inventory": {
    code: "PB-06",
    title: "Inventory Brain",
    titleTh: "สมองห้อง",
    why: "Engine 06 decides who gets scarce rooms — MinLOS, protection, stop-sell — before you discount.",
    whyTh: "เครื่อง 06 ตัดสินว่าใครได้ห้องที่ขาด — ขั้นต่ำ กันห้อง ปิดขาย — ก่อนลดราคา",
    steps: [
      { en: "Read Garden ARI. Approve MinLOS 2 on 24–25 Aug.", th: "อ่าน ARI สวน อนุมัติขั้นต่ำ 2 คืน 24–25 ส.ค." },
      { en: "Watch allotment on the right — Direct should rise when OTA rooms move.", th: "ดูจัดสรรด้านขวา — จองตรงควรขึ้นเมื่อห้อง OTA ถูกย้าย" },
      { en: "Cancel, overbook and groups are Phase 2 (09, 10, 12).", th: "ยกเลิก ขายเกิน และกรุ๊ปอยู่เฟส 2 (09, 10, 12)" },
    ],
    look: "A ฿2,700 group should not take Friday Garden. Late demand is already in the forecast.",
    lookTh: "กรุ๊ป ฿2,700 ไม่ควรได้สวนวันศุกร์ ดีมานด์ท้ายอยู่ในพยากรณ์แล้ว",
    seed: "Writes hit the same ARI store as /inventory.",
    seedTh: "การเขียนลงคลัง ARI เดียวกับ /inventory",
    engines: ["inv"],
  },
  "/rev-distribution": {
    code: "PB-07",
    title: "Distribution Brain",
    titleTh: "สมองช่องทาง",
    why: "Engine 07 maximises Net ADR, not advertised ADR. Weak demand opens every channel. Compression closes the cheapest first.",
    whyTh: "เครื่อง 07 เน้น Net ADR ไม่ใช่ ADR หน้าเว็บ ดีมานด์อ่อนเปิดทุกช่อง ตลาดบีบปิดช่องถูกก่อน",
    steps: [
      { en: "Compare Net ADR: Direct / Agent Direct versus Agoda.", th: "เทียบ Net ADR: จองตรง / Agent Direct กับ Agoda" },
      { en: "Approve the Expedia close — four Garden rooms move to Direct.", th: "อนุมัติการปิด Expedia — สวน 4 ห้องย้ายไปจองตรง" },
      { en: "Allocation, promo and conversion are engines 13–15.", th: "จัดสรร โปร และแปลงคือเครื่อง 13–15" },
    ],
    look: "Monday breakfast (no cut) is the promo diagnosis — not a 20% flash sale.",
    lookTh: "อาหารเช้าวันจันทร์ (ไม่ตัด) คือการวินิจฉัยโปร — ไม่ใช่แฟลชเซล 20%",
    seed: "Net ADR table is seeded from the profit analyser.",
    seedTh: "ตาราง Net ADR จำลองจากเครื่องวิเคราะห์กำไร",
    engines: ["channel"],
  },
  "/rev-guardian": {
    code: "PB-08",
    title: "Revenue Guardian",
    titleTh: "ผู้พิทักษ์รายได้",
    why: "Mandatory if HOTEL24 executes. A separate agent. Drafts may be stupid. This page is the fence.",
    whyTh: "บังคับถ้า HOTEL24 ลงมือเอง เป็นเอเจนต์แยก ร่างอาจโง่ หน้านี้คือรั้ว",
    steps: [
      { en: "Read the seven rails — floor, 30% cap, overbook, close-all, parity, date span, anomaly.", th: "อ่านรั้วเจ็ดข้อ — พื้น เพดาน 30% ขายเกิน ปิดหมด พาร์ตี้ จำนวนวัน ความผิดปกติ" },
      { en: "Confirm both blocked cards: Suite ฿500 and sell limit 52.", th: "ยืนยันการ์ดบล็อกทั้งคู่: สวีท ฿500 และเพดานขาย 52" },
    ],
    look: "Owner sets floors. Guardian enforces them on Autopilot L2/L3 and on the Director.",
    lookTh: "เจ้าของตั้งพื้น Guardian บังคับทั้งออโตไพลอต L2/L3 และผู้อำนวยการ",
    seed: "No override that types past the floor is offered in this demo.",
    seedTh: "เดโมนี้ไม่มีปุ่มฝ่าฝืนที่พิมพ์ข้ามพื้น",
    engines: ["guard"],
  },
  "/rev-twin": {
    code: "PB-TW",
    title: "Digital Twin",
    titleTh: "ฝาแฝดดิจิทัล",
    why: "Ask “what if I raise 15%?” before anyone writes. The twin is why scenario B ships.",
    whyTh: "ถาม “ถ้าขึ้น 15% จะเกิดอะไร” ก่อนมีใครเขียน ฝาแฝดคือเหตุผลที่สถานการณ์ B ถูกใช้",
    steps: [
      { en: "Compare hold / +11% / +29% on Garden Monday.", th: "เทียบคงราคา / +11% / +29% บนสวนวันจันทร์" },
      { en: "B wins RevPAR and net. C looks strong and loses.", th: "B ชนะ RevPAR และสุทธิ C ดูแรงแล้วแพ้" },
    ],
    look: "Phase 3 label in the catalog — shipped as a Phase 1 wow on a seeded curve.",
    lookTh: "ในรายการติดป้ายเฟส 3 — ส่งเป็นของว้าวเฟส 1 บนเส้นโค้งจำลอง",
    seed: "Not a live Monte Carlo.",
    seedTh: "ไม่ใช่ Monte Carlo สด",
    engines: ["twin"],
  },
  "/rev-decisions": {
    code: "PB-LED",
    title: "Decision ledger",
    titleTh: "สมุดตัดสิน",
    why: "Every write, block and dismissal is recorded: old BAR, new BAR, engines, expected ฿, Guardian result.",
    whyTh: "ทุกการเขียน บล็อก และไม่ทำถูกบันทึก: BAR เดิม BAR ใหม่ เครื่องยนต์ ฿ ที่คาด ผล Guardian",
    steps: [
      { en: "Approve something on the Director, then come back — status moves to applied.", th: "อนุมัติอะไรที่ผู้อำนวยการ แล้วกลับมา — สถานะเป็น applied" },
      { en: "Blocked rows never become applied.", th: "แถวที่บล็อกไม่กลายเป็น applied" },
    ],
    look: "The learning loop is observe → predict → decide → act → measure → learn.",
    lookTh: "วงจรเรียนรู้คือ สังเกต → ทำนาย → ตัดสิน → ลงมือ → วัด → เรียน",
    seed: "Attribution on this page is last-month contribution, also seeded.",
    seedTh: "ส่วนร่วมบนหน้านี้คือเดือนที่แล้ว และเป็นข้อมูลจำลอง",
  },
  "/rev-cancel": {
    code: "PB-09",
    title: "Cancel risk",
    titleTh: "เสี่ยงยกเลิก",
    why: "Engine 09 scores each folio. Soft rooms feed overbooking. Hard rooms stay sold.",
    whyTh: "เครื่อง 09 ให้คะแนนแต่ละโฟลิโอ ห้องนิ่มป้อนเครื่องขายเกิน ห้องแข็งถือว่าขายแล้ว",
    steps: [
      { en: "Sort with your eye: Lim 67% is the watch. Müller 11% is firm.", th: "กวาดตา: Lim 67% คือรายการเฝ้า Müller 11% แน่น" },
      { en: "Approve the watch-note. Do not re-sell that Pool at BAR.", th: "อนุมัติบันทึกเฝ้า อย่าปล่อยพูลนั้นที่ BAR ซ้ำ" },
    ],
    look: "Refundable + long lead + OTA + rate above the guest’s history raises the score.",
    lookTh: "คืนเงินได้ + lead ยาว + OTA + ราคาสูงกว่าประวัติแขก ดันคะแนนขึ้น",
    seed: "Seeded scores. Not live LightGBM.",
    seedTh: "คะแนนจำลอง ไม่ใช่ LightGBM สด",
    engines: ["cancel"],
  },
  "/rev-overbook": {
    code: "PB-10",
    title: "Sell limit",
    titleTh: "เพดานขาย",
    why: "Engine 10 sets how many rooms you may sell above 42. Guardian’s owner cap is +4.",
    whyTh: "เครื่อง 10 ตั้งว่าขายเกิน 42 ได้กี่ห้อง เพดานเจ้าของของ Guardian คือ +4",
    steps: [
      { en: "Read Friday: 44 on books, wash 3.2, pick sell 45.", th: "อ่านวันศุกร์: จอง 44 คาดว่าง 3.2 เลือกเพดาน 45" },
      { en: "Approve the 45 write. Confirm 52 stays blocked.", th: "อนุมัติการเขียน 45 ยืนยันว่า 52 ยังบล็อก" },
    ],
    look: "Empty-room cost ฿2,200 versus walk ฿6,800 is why 45 wins and 52 does not.",
    lookTh: "ต้นทุนห้องว่าง ฿2,200 เทียบวอล์ก ฿6,800 คือเหตุผลที่ 45 ชนะและ 52 ไม่ชนะ",
    seed: "Wash numbers are seeded from engine 09, not a live no-show feed.",
    seedTh: "ตัวเลขห้องที่อาจว่างจำลองจากเครื่อง 09 ไม่ใช่ฟีด no-show สด",
    engines: ["overbook"],
  },
  "/rev-elasticity": {
    code: "PB-11",
    title: "Willingness to pay",
    titleTh: "ความเต็มใจจ่าย",
    why: "Engine 11 stops Pricing AI jumping a breakpoint. ฿2,200 is allowed. ฿2,550 on a soft Monday is not.",
    whyTh: "เครื่อง 11 ห้ามเอเจนต์ราคากระโดดจุดหัก ฿2,200 ได้ ฿2,550 วันจันทร์อ่อนไม่ได้",
    steps: [
      { en: "Find the −19% leisure / mobile / Agoda row.", th: "หาแถวเที่ยว / มือถือ / Agoda ที่ −19%" },
      { en: "Approve the hold — it does not write a new BAR.", th: "อนุมัติการคงราคา — ไม่เขียน BAR ใหม่" },
    ],
    look: "Safe step ฿1,980 → ฿2,200 is only −3%. That is the Phase 1 write.",
    lookTh: "ขั้นปลอดภัย ฿1,980 → ฿2,200 ตกแค่ −3% นั่นคือการเขียนเฟส 1",
    seed: "Learned elasticities are seeded.",
    seedTh: "ความยืดหยุ่นที่เรียนรู้เป็นข้อมูลจำลอง",
    engines: ["elastic"],
  },
  "/rev-group": {
    code: "PB-12",
    title: "Group RFPs",
    titleTh: "ใบขอกรุ๊ป",
    why: "Engine 12: group + F&B − displaced transient. ABC at ฿2,700 is a reject. Counter ฿3,550.",
    whyTh: "เครื่อง 12: กรุ๊ป + อาหาร − แขกเดินที่เบียด ABC ที่ ฿2,700 คือปฏิเสธ เสนอ ฿3,550",
    steps: [
      { en: "Read the ABC row — net −฿8,600 if you take ฿2,700.", th: "อ่านแถว ABC — สุทธิ −฿8,600 ถ้ารับ ฿2,700" },
      { en: "Approve reject + counter. Inventory is not written until sales accepts.", th: "อนุมัติปฏิเสธ + ราคาเสนอ ยังไม่เขียนห้องจนกว่าฝ่ายขายรับ" },
    ],
    look: "TAT fam and Oman crew are accepts — displacement is covered.",
    lookTh: "ทริป TAT และลูกเรือโอมานคือรับ — การเบียดคุ้ม",
    seed: "RFPs are seeded. No live CRM.",
    seedTh: "ใบขอจำลอง ไม่มี CRM สด",
    engines: ["group"],
  },
  "/rev-alloc": {
    code: "PB-13",
    title: "Channel allocation",
    titleTh: "จัดสรรช่องทาง",
    why: "Engine 13 moves rooms as the market tightens. Last rooms to Direct. Booking stays open.",
    whyTh: "เครื่อง 13 ย้ายห้องเมื่อตลาดแน่น ห้องท้ายให้จองตรง Booking ยังเปิด",
    steps: [
      { en: "Read the Compression row — that is today’s pick.", th: "อ่านแถว Compression — นั่นคือตัวเลือกวันนี้" },
      { en: "Approve Booking 12 → 8. Watch live allotment on the right.", th: "อนุมัติ Booking 12 → 8 ดูจัดสรรจริงด้านขวา" },
    ],
    look: "Expedia is already 0 in compression. Guardian forbids closing every channel.",
    lookTh: "Expedia เป็น 0 แล้วตอนตลาดบีบ Guardian ห้ามปิดทุกช่อง",
    seed: "State table is seeded. Writes hit the same allotment store as Autopilot.",
    seedTh: "ตารางสภาวะจำลอง การเขียนลงคลังจัดสรรเดียวกับออโตไพลอต",
    engines: ["alloc"],
  },
  "/rev-promo": {
    code: "PB-14",
    title: "Promotion test",
    titleTh: "ทดสอบโปร",
    why: "Engine 14 asks PRICE or DEMAND before anyone discounts. Monday is demand. Breakfast wins.",
    whyTh: "เครื่อง 14 ถามว่าราคาหรือดีมานด์ก่อนมีใครลด วันจันทร์คือดีมานด์ อาหารเช้าชนะ",
    steps: [
      { en: "Read the five options. C is highlighted: no cut + breakfast.", th: "อ่านห้าตัวเลือก C ถูกไฮไลต์: ไม่ตัด + อาหารเช้า" },
      { en: "Approve Option C. BAR does not move. Direct inclusion turns on.", th: "อนุมัติตัวเลือก C BAR ไม่ขยับ สิทธิ์จองตรงเปิด" },
    ],
    look: "20% off is occupancy vanity: +4pp, −฿18,200.",
    lookTh: "ลด 20% คือเข้าพักโอ้อวด: +4 จุด, −฿18,200",
    seed: "Simulation is seeded on the weekday Garden curve.",
    seedTh: "การจำลองอยู่บนเส้นโค้งสวนวันธรรมดา",
    engines: ["promo"],
  },
  "/rev-convert": {
    code: "PB-15",
    title: "Direct conversion",
    titleTh: "แปลงจองตรง",
    why: "Engine 15 recovers an abandoned search with an inclusion. Feeds Agent Direct. No public undercut.",
    whyTh: "เครื่อง 15 กู้เซสชันที่ทิ้งด้วยสิทธิ์ ต่อเข้า Agent Direct ไม่ตัดราคาหน้าเว็บ",
    steps: [
      { en: "Open S-4419 — Sydney mobile, dropped on payment, 71%.", th: "เปิด S-4419 — มือถือซิดนีย์ ทิ้งตอนจ่าย 71%" },
      { en: "Approve the free-cancel offer. Status moves to sent.", th: "อนุมัติข้อเสนอยกเลิกฟรี สถานะเป็น sent" },
    ],
    look: "A ฿200 Agoda match would be a parity violation. Guardian would block a public cut.",
    lookTh: "ตัดเท่า Agoda ฿200 คือผิดพาร์ตี้ Guardian จะบล็อกการตัดหน้าเว็บ",
    seed: "Sessions are seeded. Not a live pixel.",
    seedTh: "เซสชันจำลอง ไม่ใช่พิกเซลสด",
    engines: ["direct"],
  },
  "/rev-attribution": {
    code: "PB-16",
    title: "Why it moved",
    titleTh: "ทำไมรายได้ขยับ",
    why: "Engine 16 explains the variance. It never writes ARI. Next month is 8.7% below budget.",
    whyTh: "เครื่อง 16 อธิบายส่วนต่าง ไม่เขียน ARI เดือนหน้าต่ำกว่างบ 8.7%",
    steps: [
      { en: "Read the vs-budget split — Singapore, OTA visibility, corporate.", th: "อ่านการแยกเทียบงบ — สิงคโปร์ การมองเห็น OTA คอร์ปอเรต" },
      { en: "Use last-month contribution to brief the owner. Do not hunt a write here.", th: "ใช้ส่วนร่วมเดือนที่แล้วบรีฟเจ้าของ อย่าลางานเขียนในหน้านี้" },
    ],
    look: "If every miss is “the market”, the Director cannot learn.",
    lookTh: "ถ้าทุกส่วนต่างคือ “ตลาด” ผู้อำนวยการเรียนรู้ไม่ได้",
    seed: "Seeded variance — not a live econometric model.",
    seedTh: "ส่วนต่างจำลอง — ไม่ใช่โมเดลเศรษฐมิติจริง",
    engines: ["attr"],
  },
  "/gm": {
    code: "PB-GM",
    title: "AI General Manager",
    titleTh: "GM อัตโนมัติ",
    why: "Watches the house the way a GM would. Proposes. You approve — each tap writes the same store as calendar, HK and sync.",
    whyTh: "ดูโรงแรมแบบ GM เสนอมา คุณกดอนุมัติ — แต่ละครั้งเขียนคลังเดียวกับปฏิทิน แม่บ้าน และซิงก์",
    steps: [
      { en: "Read High items first — oversell, unpaid, TM30, dirty rooms before 14:00.", th: "อ่านรายการสูงก่อน — ขายเกิน ค้างชำระ TM30 ห้องสกปรกก่อน 14:00" },
      { en: "Approve one, or Approve all high.", th: "อนุมัติทีละรายการ หรืออนุมัติรายการสูงทั้งหมด" },
      { en: "Follow the href on a card if you want the operational screen.", th: "ตามลิงก์บนการ์ดถ้าต้องการหน้าปฏิบัติการ" },
    ],
    look: "Family Loft unmapped on Expedia is the classic oversell. Mapping it is a GM write.",
    lookTh: "แฟมิลี่ลอฟท์ยังไม่ map บน Expedia คือขายเกินคลาสสิก การ map คืองานเขียนของ GM",
    seed: "Seven house engines share this action store. Not a live camera feed.",
    seedTh: "เจ็ดเครื่องยนต์บ้านใช้คลังงานนี้ร่วมกัน ไม่ใช่กล้องสด",
  },
  "/autopilot": {
    code: "PB-AP",
    title: "Revenue Autopilot",
    titleTh: "ออโตไพลอตรายได้",
    why: "The older single-queue writer: rates, min-stay, last-minute, which OTA holds the room — ranked by net, not by who shouts.",
    whyTh: "คิวเขียนแบบเก่า: ราคา ขั้นต่ำ นาทีสุดท้าย OTA ไหนกันห้อง — เรียงจากสุทธิ ไม่ใช่จากใครตะโกน",
    steps: [
      { en: "Use this to show a simple queue. Use RevenueOS for the department.", th: "ใช้หน้านี้โชว์คิวสั้น ใช้ RevenueOS เมื่อโชว์ทั้งฝ่าย" },
      { en: "Approve a rate or allotment — it writes the same ARI / allotment store.", th: "อนุมัติราคาหรือจัดสรร — เขียนคลัง ARI / จัดสรรเดียวกัน" },
    ],
    look: "Garden weekend ฿2,200 → ฿2,550 and four Agoda rooms to Direct live here too.",
    lookTh: "สวนสุดสัปดาห์ ฿2,200 → ฿2,550 และห้อง Agoda 4 ห้องไปจองตรงก็อยู่ที่นี่",
    seed: "Do not replace this with RevenueOS. Two writers, one store.",
    seedTh: "อย่าแทนหน้านี้ด้วย RevenueOS สองตัวเขียน คลังเดียว",
  },
  "/agent": {
    code: "PB-GA",
    title: "Guest Agent",
    titleTh: "เอเจนต์แขก",
    why: "Not a chatbot. Creates, modifies, cancels, holds a clean room, adds a transfer — still escalates refunds.",
    whyTh: "ไม่ใช่แชทบอท สร้าง แก้ ยกเลิก กันห้องสะอาด ใส่รถรับ — ยังส่งเรื่องคืนเงินต่อคน",
    steps: [
      { en: "Approve the early check-in or transfer add-on.", th: "อนุมัติเช็คอินเช้าหรือรถรับ" },
      { en: "Refunds stay outside AI authority — escalate.", th: "คืนเงินอยู่นอกอำนาจ AI — ส่งต่อคน" },
    ],
    look: "Inbox is the thread. This page is the ops queue behind it.",
    lookTh: "กล่องข้อความคือเธรด หน้านี้คือคิวปฏิบัติการข้างหลัง",
    seed: "Scripts are seeded. Compensation is never auto-applied.",
    seedTh: "สคริปต์จำลอง ค่าชดเชยไม่ถูกใช้อัตโนมัติ",
  },
  "/reconcile": {
    code: "PB-RC",
    title: "OTA Reconcile",
    titleTh: "กระทบยอด OTA",
    why: "HOTEL24 is the system of record. Remotes are forced to the master when they drift.",
    whyTh: "HOTEL24 เป็นต้นฉบับ ฝั่ง OTA ถูกบังคับให้ตามเมื่อคลาด",
    steps: [
      { en: "Run reconcile. Trip.com Garden 20 Aug showing 2 against master 3 is the demo.", th: "รันกระทบยอด Trip.com สวน 20 ส.ค. โชว์ 2 ต้นฉบับ 3 คือเดโม" },
      { en: "Force, then recheck. Alert only if it cannot close.", th: "บังคับ แล้วตรวจซ้ำ เตือนเมื่อปิดเองไม่ได้" },
    ],
    look: "Mismatch, duplicate, stale ARI, failed import — auto-resync first.",
    lookTh: "ไม่ตรง จองซ้ำ ARI ค้าง นำเข้าล้ม — ซิงก์อัตโนมัติก่อน",
    seed: "Comparison is seeded. Not a live Channex poll on a timer.",
    seedTh: "การเทียบจำลอง ไม่ใช่โพล Channex ตามเวลาจริง",
  },
  "/reputation": {
    code: "PB-REP",
    title: "Reputation → Ops",
    titleTh: "รีวิว → ปฏิบัติการ",
    why: "A 2-star Google review is a room, a breakfast shift or a vacuum — not a marketing problem.",
    whyTh: "รีวิว Google 2 ดาวคือห้อง กะอาหารเช้า หรือเครื่องดูดฝุ่น — ไม่ใช่ปัญหาการตลาด",
    steps: [
      { en: "Extract the defect, open the ticket, then draft the public reply.", th: "ดึงจุดเสีย เปิดงาน แล้วค่อยร่างตอบสาธารณะ" },
      { en: "Never refund in public. Approve the HK / F&B move first.", th: "ห้ามคืนเงินในที่สาธารณะ อนุมัติงานแม่บ้าน / อาหารก่อน" },
    ],
    look: "209 aircon → move to 301. Three slow-breakfast mentions → +2 F&B 08:00–09:30.",
    lookTh: "209 แอร์ → ย้าย 301 พูดอาหารเช้าช้าสามครั้ง → เพิ่มพนักงานอาหาร 2 คน 08:00–09:30",
    seed: "Reviews are seeded. No live Google API.",
    seedTh: "รีวิวจำลอง ไม่มี Google API สด",
  },
  "/migrate": {
    code: "PB-MIG",
    title: "Migration Agent",
    titleTh: "เอเจนต์ย้ายระบบ",
    why: "Cloudbeds and Little Hotelier do not arrive clean. The agent maps rooms and rates with a confidence score.",
    whyTh: "Cloudbeds กับ Little Hotelier ไม่ได้มาสะอาด เอเจนต์ map ห้องและเรท พร้อมคะแนนความมั่นใจ",
    steps: [
      { en: "Read Family Loft → Expedia Family Loft at 96%.", th: "อ่านแฟมิลี่ลอฟท์ → Expedia Family Loft ที่ 96%" },
      { en: "Cut-over lives on Switch — only when Shield will pass.", th: "การตัดสลับอยู่ที่หน้า Switch — เมื่อ Shield จะผ่าน" },
    ],
    look: "Müller’s two source ids merge into H24-8802.",
    lookTh: "สองไอดีต้นทางของมุลเลอร์รวมเป็น H24-8802",
    seed: "Maps are proposed, not pulled from a live Cloudbeds token in this demo.",
    seedTh: "แผนที่ถูกเสนอ ไม่ได้ดึงจากโทเคน Cloudbeds สดในเดโมนี้",
  },
  "/line": {
    code: "PB-LN",
    title: "Morning Brief",
    titleTh: "สรุปเช้า",
    why: "A brief without a button is a report. Each LINE row is a decision that writes HOTEL24.",
    whyTh: "สรุปที่ไม่มีปุ่มคือรายงาน แต่ละบรรทัดบน LINE คือการตัดสินใจที่เขียน HOTEL24",
    steps: [
      { en: "Approve mapping, collection, rate or room move from the thread.", th: "อนุมัติ map เก็บเงิน ราคา หรือย้ายห้องจากเธรด" },
      { en: "Thai owners already live in that chat — this is the console twin.", th: "เจ้าของไทยอยู่ในแชทนั้นอยู่แล้ว — นี่คือฝาแฝดบนคอนโซล" },
    ],
    look: "Same actions as the GM, filtered for the morning brief.",
    lookTh: "งานเดียวกับ GM กรองสำหรับสรุปเช้า",
    seed: "LINE is simulated. No live LINE Official Account token required.",
    seedTh: "LINE จำลอง ไม่ต้องมีโทเคนบัญชีทางการ",
  },
  "/reservations": {
    code: "PB-RES",
    title: "Reservations",
    titleTh: "ปฏิทินการจอง",
    why: "One calendar. Grey weights are OTAs. Red is Direct, AI and Agent Direct.",
    whyTh: "ปฏิทินเดียว น้ำหนักเทาคือ OTA แดงคือจองตรง AI และ Agent Direct",
    steps: [
      { en: "Filter a date. Open a stay. Walk-in and new reservation sit on this store.", th: "กรองวันที่ เปิดการเข้าพัก วอล์กอินและจองใหม่ลงคลังนี้" },
      { en: "Agent Direct books appear with commission ฿0.", th: "จอง Agent Direct โชว์คอม ฿0" },
    ],
    look: "This calendar is the system of record. OTAs are forced to it.",
    lookTh: "ปฏิทินนี้คือต้นฉบับ OTA ถูกบังคับให้ตาม",
    seed: "Baan Talay August graph is seeded.",
    seedTh: "กราฟสิงหาคมบ้านทะเลเป็นข้อมูลจำลอง",
  },
  "/front-desk": {
    code: "PB-FD",
    title: "Front Desk",
    titleTh: "หน้าเคาน์เตอร์",
    why: "Check-in, check-out, room assign, deposit, passport scan. TM30 starts here.",
    whyTh: "เช็คอิน เช็คเอาท์ จัดห้อง มัดจำ สแกนพาสปอร์ต TM30 เริ่มที่นี่",
    steps: [
      { en: "Check in an arrival. Collect the due if it is unpaid.", th: "เช็คอินแขกเข้า เก็บค้างชำระถ้ายังไม่จ่าย" },
      { en: "Scan passport, then file TM30 from Compliance if needed.", th: "สแกนพาสปอร์ต แล้วยื่น TM30 ที่หน้าคอมไพลแอนซ์ถ้าต้อง" },
    ],
    look: "Unpaid arrivals are a GM high item pointing back here.",
    lookTh: "แขกค้างชำระคือรายการสูงของ GM ที่ชี้กลับมาที่นี่",
    seed: "Folios are seeded. PromptPay is labelled, not charged.",
    seedTh: "โฟลิโอจำลอง PromptPay มีป้าย ไม่ได้ตัดบัตร",
  },
  "/housekeeping": {
    code: "PB-HK",
    title: "Housekeeping",
    titleTh: "แม่บ้าน",
    why: "Room status the desk and the GM both trust. Dirty rooms before 14:00 are a GM high.",
    whyTh: "สถานะห้องที่เคาน์เตอร์และ GM เชื่อด้วยกัน ห้องสกปรกก่อน 14:00 คือรายการสูงของ GM",
    steps: [
      { en: "Advance a room clean → inspect → ready.", th: "เดินห้อง สกปรก → ตรวจ → พร้อม" },
      { en: "Auto-assign if the board is uneven.", th: "จัดอัตโนมัติถ้ากระดานไม่สมดุล" },
    ],
    look: "Reputation tickets (209 aircon) land here as work, not as a reply.",
    lookTh: "ตั๋วรีวิว (209 แอร์) มาเป็นงาน ไม่ใช่เป็นคำตอบ",
    seed: "Board is seeded for today.",
    seedTh: "กระดานจำลองสำหรับวันนี้",
  },
  "/inbox": {
    code: "PB-IN",
    title: "Guest Inbox",
    titleTh: "กล่องข้อความแขก",
    why: "Guest threads in their language. The Guest Agent drafts. You send. Refunds escalate.",
    whyTh: "เธรดแขกในภาษาแขก เอเจนต์แขกร่าง คุณส่ง คืนเงินส่งต่อคน",
    steps: [
      { en: "Pick a thread. Send the draft or edit it.", th: "เลือกเธรด ส่งฉบับร่างหรือแก้" },
      { en: "Upgrade offers from RevenueOS can queue here in Phase 3.", th: "ข้อเสนออัปเกรดจาก RevenueOS คิวที่นี่ได้ในเฟส 3" },
    ],
    look: "This is not Agent Direct. Agent Direct is machines booking. Inbox is humans talking.",
    lookTh: "นี่ไม่ใช่ Agent Direct Agent Direct คือเครื่องจอง กล่องนี้คือคนคุย",
    seed: "Threads are seeded.",
    seedTh: "เธรดจำลอง",
  },
  "/rates": {
    code: "PB-RT",
    title: "Rate & AI Revenue",
    titleTh: "ราคาห้อง & AI",
    why: "The working rate grid plus the older AI revenue recommendations. RevenueOS is the department; this is the grid.",
    whyTh: "ตารางราคาที่ใช้จริงบวกคำแนะนำรายได้แบบเก่า RevenueOS คือฝ่าย นี่คือตาราง",
    steps: [
      { en: "Read BAR by room type. Open RevenueOS for why a cell should move.", th: "อ่าน BAR ต่อประเภทห้อง เปิด RevenueOS ถ้าถามว่าทำไมเซลล์ควรขยับ" },
      { en: "Approve an Autopilot rate if you want a write without the Director.", th: "อนุมัติราคาออโตไพลอตถ้าจะเขียนโดยไม่ผ่านผู้อำนวยการ" },
    ],
    look: "Same ARI store. Two UIs.",
    lookTh: "คลัง ARI เดียว สองหน้าจอ",
    seed: "Recommendations overlap RevenueOS on purpose.",
    seedTh: "คำแนะนำทับ RevenueOS โดยตั้งใจ",
  },
  "/profit": {
    code: "PB-PF",
    title: "OTA Profit",
    titleTh: "กำไรจริงต่อช่องทาง",
    why: "Gross minus commission, promo and fees. This is the number engine 07 uses.",
    whyTh: "ยอดก่อนหัก ลบคอม โปร และค่าธรรมเนียม นี่คือตัวเลขที่เครื่อง 07 ใช้",
    steps: [
      { en: "Compare Direct net ADR to Agoda.", th: "เทียบ Net ADR จองตรงกับ Agoda" },
      { en: "Take that story into Distribution Brain or Autopilot allotment.", th: "เอาเรื่องนั้นไปสมองช่องทางหรือจัดสรรออโตไพลอต" },
    ],
    look: "Agoda sold more and still lost ฿751 per night versus Direct.",
    lookTh: "Agoda ขายมากกว่าแล้วยังแพ้จองตรง ฿751 ต่อคืน",
    seed: "Month totals are seeded.",
    seedTh: "ยอดเดือนจำลอง",
  },
  "/direct": {
    code: "PB-DR",
    title: "Direct Booking",
    titleTh: "จองตรง",
    why: "The hotel’s own booking page and mix. Agent Direct books count as Direct — you own the guest.",
    whyTh: "หน้าจองของโรงแรมเองและส่วนผสม จอง Agent Direct นับเป็นจองตรง — คุณเป็นเจ้าของแขก",
    steps: [
      { en: "Open /book/baantalay as a guest would.", th: "เปิด /book/baantalay แบบแขก" },
      { en: "Watch allotment: last rooms should lean Direct in compression.", th: "ดูจัดสรร: ห้องท้ายควรเอียงจองตรงเมื่อตลาดบีบ" },
    ],
    look: "Red on the calendar is this channel plus AI.",
    lookTh: "สีแดงบนปฏิทินคือช่องนี้บวก AI",
    seed: "Public booking page is real in the demo; payment is not charged.",
    seedTh: "หน้าจองสาธารณะมีจริงในเดโม ไม่ได้ตัดเงิน",
  },
  "/channels": {
    code: "PB-CH",
    title: "Connection Center",
    titleTh: "ศูนย์ช่องทาง",
    why: "White-label OTA connections. Channex first. OTAs are a channel — not the centre.",
    whyTh: "การเชื่อม OTA แบบไวท์เลเบล เริ่มที่ Channex OTA เป็นช่องทาง — ไม่ใช่ศูนย์กลาง",
    steps: [
      { en: "Read channel health. Pause Agoda only if you mean it — Shield will notice.", th: "อ่านสุขภาพช่อง หยุด Agoda เมื่อตั้งใจ — Shield จะเห็น" },
      { en: "Overbooking Shield on this page is the connectivity fence, not Revenue Guardian.", th: "Overbooking Shield ในหน้านี้คือรั้วเชื่อมต่อ ไม่ใช่ Revenue Guardian" },
    ],
    look: "61+ channels is the Channex story. This demo shows the core four plus Direct.",
    lookTh: "61+ ช่องทางคือเรื่อง Channex เดโมนี้โชว์สี่ช่องหลักบวกจองตรง",
    seed: "Tokens are not live. Do not start with direct Booking.com Connectivity.",
    seedTh: "โทเคนไม่สด อย่าเริ่มด้วย Booking.com Connectivity โดยตรง",
  },
  "/mapping": {
    code: "PB-MAP",
    title: "OTA Mapping",
    titleTh: "จับคู่ OTA",
    why: "Canonical HOTEL24 rooms mapped to each OTA. Unmapped types oversell.",
    whyTh: "ห้องต้นฉบับ HOTEL24 จับคู่แต่ละ OTA ประเภทที่ยังไม่ map คือขายเกิน",
    steps: [
      { en: "Fix Family Loft → Expedia Family Loft. That is the GM’s first high item.", th: "แก้แฟมิลี่ลอฟท์ → Expedia Family Loft นั่นคือรายการสูงแรกของ GM" },
      { en: "Confidence scores come from the Migration Agent.", th: "คะแนนความมั่นใจมาจากเอเจนต์ย้ายระบบ" },
    ],
    look: "One HOTEL24 room type. Many remote names.",
    lookTh: "หนึ่งประเภทห้อง HOTEL24 หลายชื่อฝั่ง OTA",
    seed: "Maps are seeded / proposed.",
    seedTh: "แผนที่จำลอง / ถูกเสนอ",
  },
  "/inventory": {
    code: "PB-ARI",
    title: "Inventory & ARI",
    titleTh: "ห้องคงเหลือ & ARI",
    why: "The heart of HOTEL24. Availability, BAR, restriction — the master OTAs must follow.",
    whyTh: "หัวใจของ HOTEL24 ห้องว่าง BAR ข้อจำกัด — ต้นฉบับที่ OTA ต้องตาม",
    steps: [
      { en: "Pick a room type. Read avail / BAR / MinLOS. RevenueOS writes land here.", th: "เลือกประเภทห้อง อ่านว่าง / BAR / ขั้นต่ำ งานเขียน RevenueOS ลงที่นี่" },
      { en: "Push ARI only after you intend the remotes to move.", th: "ดัน ARI เมื่อตั้งใจให้ฝั่ง OTA ขยับ" },
    ],
    look: "Garden Monday BAR moves to ฿2,200 after the Director write.",
    lookTh: "BAR สวนวันจันทร์เป็น ฿2,200 หลังผู้อำนวยการเขียน",
    seed: "Grid is seeded. Push is a demo job, not a live Channex post.",
    seedTh: "ตารางจำลอง การดันคืองานเดโม ไม่ใช่โพสต์ Channex สด",
  },
  "/sync": {
    code: "PB-SY",
    title: "OTA Sync",
    titleTh: "ซิงก์ OTA",
    why: "Never call the provider from the browser. Jobs go through the queue: ARI, RES, MAP, ACK.",
    whyTh: "ห้ามเรียกผู้ให้บริการจากเบราว์เซอร์ งานผ่านคิว: ARI, RES, MAP, ACK",
    steps: [
      { en: "Retry a failed job. Receive a webhook. Apply a modification or cancel.", th: "ลองงานที่ล้มอีกครั้ง รับเว็บฮุก ใช้การแก้หรือยกเลิก" },
      { en: "RevenueOS writes appear here as completed ARI / RES jobs.", th: "งานเขียน RevenueOS โผล่ที่นี่เป็นงาน ARI / RES ที่เสร็จ" },
    ],
    look: "Stale ARI and retries are the GM’s connectivity items.",
    lookTh: "ARI ค้างและการลองใหม่คือรายการเชื่อมต่อของ GM",
    seed: "Queue is seeded plus session writes. Not a live worker.",
    seedTh: "คิวจำลองบวกงานในรอบนี้ ไม่ใช่เวิร์กเกอร์สด",
  },
  "/dashboard": {
    code: "PB-OW",
    title: "Owner Dashboard",
    titleTh: "ภาพรวมเจ้าของ",
    why: "Occupancy, ADR, RevPAR — the owner glance. Not where writes happen.",
    whyTh: "เข้าพัก ADR RevPAR — ภาพรวมเจ้าของ ไม่ใช่ที่เขียนงาน",
    steps: [
      { en: "Read the house vs last year. Dive into RevenueOS if you want the why.", th: "อ่านบ้านเทียบปีที่แล้ว ลง RevenueOS ถ้าอยากรู้ว่าทำไม" },
      { en: "Morning Brief is the same story with buttons.", th: "สรุปเช้าคือเรื่องเดียวกันแต่มีปุ่ม" },
    ],
    look: "Baan Talay 42 rooms. Red is Direct / AI mix.",
    lookTh: "บ้านทะเล 42 ห้อง แดงคือส่วนจองตรง / AI",
    seed: "KPIs are seeded.",
    seedTh: "KPI จำลอง",
  },
  "/compliance": {
    code: "PB-TM",
    title: "Compliance TM30",
    titleTh: "TM30 และ PDPA",
    why: "Thai lodging law: passport, TM30, PDPA. The desk captures. This page files.",
    whyTh: "กฎหมายที่พักไทย: พาสปอร์ต TM30 PDPA เคาน์เตอร์เก็บ หน้านี้ยื่น",
    steps: [
      { en: "File TM30 for arrivals that have a scan.", th: "ยื่น TM30 สำหรับแขกที่มีสแกน" },
      { en: "PDPA stay on this property — do not export guest files casually.", th: "PDPA อยู่ที่โรงแรมนี้ — อย่าส่งไฟล์แขกออกไปมั่ว" },
    ],
    look: "Unfiled TM30 is a GM high item.",
    lookTh: "TM30 ยังไม่ยื่นคือรายการสูงของ GM",
    seed: "Filing is a demo stamp, not a live Immigration post.",
    seedTh: "การยื่นคือตราเดโม ไม่ใช่โพสต์ตรวจคนเข้าเมืองสด",
  },
  "/finance": {
    code: "PB-FN",
    title: "Finance",
    titleTh: "เงินสดและใบเสร็จ",
    why: "Cash, receipts, exceptions. The GM flags a cash miss. You acknowledge here.",
    whyTh: "เงินสด ใบเสร็จ ข้อยกเว้น GM ชี้เงินขาด คุณรับทราบที่นี่",
    steps: [
      { en: "Acknowledge the cash exception. Collect unpaid from Front Desk.", th: "รับทราบข้อยกเว้นเงินสด เก็บค้างชำระที่หน้าเคาน์เตอร์" },
      { en: "Agent Direct bookings show commission ฿0 — hotel owns the payment story.", th: "จอง Agent Direct โชว์คอม ฿0 — โรงแรมถือเรื่องการชำระ" },
    ],
    look: "Not a full accounting suite. Exceptions and deposits only.",
    lookTh: "ไม่ใช่ชุดบัญชีเต็ม มีแค่ข้อยกเว้นและมัดจำ",
    seed: "Ledgers are seeded.",
    seedTh: "สมุดจำลอง",
  },
  "/switch": {
    code: "PB-SW",
    title: "Switch from PMS",
    titleTh: "ย้ายจากระบบเดิม",
    why: "One-button cut-over from Cloudbeds or Little Hotelier after maps and Shield pass.",
    whyTh: "ตัดสลับปุ่มเดียวจาก Cloudbeds หรือ Little Hotelier หลังแผนที่และ Shield ผ่าน",
    steps: [
      { en: "Pick the source. Walk the steps. Do not start cut-over if Shield is open.", th: "เลือกต้นทาง เดินตามขั้น อย่าเริ่มตัดสลับถ้า Shield ยังเปิด" },
      { en: "Migration Agent proposes maps first.", th: "เอเจนต์ย้ายระบบเสนอแผนที่ก่อน" },
    ],
    look: "After switch, the console treats HOTEL24 as master.",
    lookTh: "หลังย้าย คอนโซลถือ HOTEL24 เป็นต้นฉบับ",
    seed: "Switch is a guided demo, not a live Cloudbeds pull.",
    seedTh: "การย้ายเป็นเดโมมีไกด์ ไม่ได้ดึง Cloudbeds สด",
  },
  "/playbook": {
    code: "PB-ALL",
    title: "Playbook index",
    titleTh: "สารบัญเพลย์บุ๊ก",
    why: "Every menu has a playbook on the page. This index lists every screen and every engine in one place.",
    whyTh: "ทุกเมนูมีเพลย์บุ๊กบนหน้านี้ สารบัญนี้รวมทุกหน้าจอและทุกเครื่องยนต์ไว้ที่เดียว",
    steps: [
      { en: "Jump to a screen. Expand an engine. Demo login: som@baantalay.com / demo1234.", th: "กระโดดไปหน้าจอ ขยายเครื่องยนต์ ล็อกอินเดโม: som@baantalay.com / demo1234" },
      { en: "Remember: seeded engines, not live ML. Guardian still blocks ฿500 and sell 52.", th: "จำไว้: เครื่องยนต์จำลอง ไม่ใช่ ML สด Guardian ยังบล็อก ฿500 และเพดาน 52" },
    ],
    look: "Sixteen official engines + compression signal + twin.",
    lookTh: "สิบหกเครื่องยนต์ทางการ + สัญญาณบีบตลาด + ฝาแฝด",
    seed: "Copy is product truth for the demo, not a live ops SOP.",
    seedTh: "ข้อความคือความจริงของเดโม ไม่ใช่ SOP ปฏิบัติการสด",
  },
};

export function playbookFor(path: string): MenuPlaybook | undefined {
  return MENU_PLAYBOOKS[path];
}

export const PLAYBOOK_GROUPS: { en: string; th: string; hrefs: string[] }[] = [
  { en: "Agent Direct", th: "Agent Direct", hrefs: ["/agent-direct", "/gateway", "/registry", "/agent-offers", "/aeo", "/hap"] },
  { en: "RevenueOS", th: "RevenueOS", hrefs: ["/rev-engines", "/rev-phase2", "/revenue-os", "/rev-demand", "/rev-pricing", "/rev-inventory", "/rev-distribution", "/rev-guardian", "/rev-twin", "/rev-decisions", "/rev-cancel", "/rev-overbook", "/rev-elasticity", "/rev-group", "/rev-alloc", "/rev-promo", "/rev-convert", "/rev-attribution"] },
  { en: "AI", th: "AI", hrefs: ["/gm", "/autopilot", "/agent", "/reconcile", "/reputation", "/migrate", "/line"] },
  { en: "Operate", th: "หน้างาน", hrefs: ["/reservations", "/front-desk", "/housekeeping", "/inbox"] },
  { en: "Revenue", th: "รายได้", hrefs: ["/rates", "/profit", "/direct"] },
  { en: "Distribution", th: "กระจายห้อง", hrefs: ["/channels", "/mapping", "/inventory", "/sync"] },
  { en: "Oversight", th: "เจ้าของกิจการ", hrefs: ["/dashboard", "/compliance", "/finance", "/switch", "/playbook"] },
];

